name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Fix Gradle permissions
        run: chmod +x Android/src/gradlew

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > Android/src/local.properties

      - name: Build APK
        run: cd Android/src && ./gradlew clean assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: Android/src/app/build/outputs/apk/debug/*.apk
